### ISSUE TITLE
Add Django 1.8, 1.9 compatability

### ISSUE THREAD

**Issue by auvipy** [coleifer/django-generic-aggregation#6]
and remove less then 1.7

**Comment by coleifer** [comment]
What needs to happen?

**Comment by auvipy** [comment]
first add django 1.8 and 1.9 in tox / test runner and see what tests fails, fixing them will add the django 1.8, 1.9 support. you may need to remove 1.5, 1.6 support as they reached the End of Life cycle.

**Comment by jdavisp3** [comment]
I'm going to work on this, FYI.
